render_compose() {
  cat <<EOF
services:
  dashboard:
    image: ${DASHBOARD_IMAGE}
    container_name: netbird-dashboard
    restart: unless-stopped
    env_file:
      - ./dashboard.env
    ports:
      - "${BIND_ADDRESS}:${DASHBOARD_PORT}:80"
    depends_on:
      - netbird-server
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  netbird-server:
    image: ${SERVER_IMAGE}
    container_name: netbird-server
    restart: unless-stopped
    environment:
      NB_DISABLE_GEOLOCATION: "true"
    ports:
      - "${BIND_ADDRESS}:${SERVER_PORT}:80"
      - "${STUN_PORT}:${STUN_PORT}/udp"
    volumes:
      - ./config:/etc/netbird:ro
      - ./data:/var/lib/netbird
    command: ["--config", "/etc/netbird/config.yaml"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
EOF
}

render_config_yaml() {
  local relay_secret="$1"
  local encryption_key="$2"
  local origin
  origin="$(public_origin)"
  cat <<EOF
# Generated by netbird-server-tui.sh
server:
  listenAddress: ":80"
  exposedAddress: "${origin}"
  stunPorts:
    - ${STUN_PORT}
  metricsPort: 9090
  healthcheckAddress: ":9000"
  logLevel: "info"
  logFile: "console"

  authSecret: "${relay_secret}"
  dataDir: "/var/lib/netbird"

  disableAnonymousMetrics: true
  disableGeoliteUpdate: true

  auth:
    issuer: "${origin}/oauth2"
    signKeyRefreshEnabled: true
    dashboardRedirectURIs:
      - "${origin}/nb-auth"
      - "${origin}/nb-silent-auth"
    cliRedirectURIs:
      - "http://localhost:53000/"

  reverseProxy:
    trustedHTTPProxies:
      - "127.0.0.1/32"
      - "172.16.0.0/12"
      - "10.0.0.0/8"
      - "192.168.0.0/16"

  store:
    engine: "sqlite"
    encryptionKey: "${encryption_key}"
EOF
}

render_dashboard_env() {
  local origin
  origin="$(public_origin)"
  cat <<EOF
# Generated by netbird-server-tui.sh
NETBIRD_MGMT_API_ENDPOINT=${origin}
NETBIRD_MGMT_GRPC_API_ENDPOINT=${origin}
AUTH_AUDIENCE=netbird-dashboard
AUTH_CLIENT_ID=netbird-dashboard
AUTH_CLIENT_SECRET=
AUTH_AUTHORITY=${origin}/oauth2
USE_AUTH0=false
AUTH_SUPPORTED_SCOPES=openid profile email groups
AUTH_REDIRECT_URI=/nb-auth
AUTH_SILENT_REDIRECT_URI=/nb-silent-auth
NGINX_SSL_PORT=443
LETSENCRYPT_DOMAIN=none
EOF
}

render_openresty_root_conf() {
  local hsts_header=""
  local dashboard_upstream server_upstream
  dashboard_upstream="$(proxy_upstream_authority "$DASHBOARD_PORT")"
  server_upstream="$(proxy_upstream_authority "$SERVER_PORT")"
  if [[ "$PUBLIC_SCHEME" == "https" ]]; then
    hsts_header='    add_header Strict-Transport-Security "max-age=31536000";'
  fi
  cat <<EOF
location ^~ /relay {
    proxy_pass http://${server_upstream};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Host \$http_host;
    proxy_set_header X-Forwarded-Port ${PUBLIC_PORT};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto ${PUBLIC_SCHEME};
    proxy_read_timeout 1d;
}

location ^~ /ws-proxy/ {
    proxy_pass http://${server_upstream};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Host \$http_host;
    proxy_set_header X-Forwarded-Port ${PUBLIC_PORT};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto ${PUBLIC_SCHEME};
    proxy_read_timeout 1d;
}

location ^~ /signalexchange.SignalExchange/ {
    grpc_pass grpc://${server_upstream};
    grpc_read_timeout 1d;
    grpc_send_timeout 1d;
    grpc_socket_keepalive on;
    grpc_set_header Host \$http_host;
    grpc_set_header X-Forwarded-Host \$http_host;
    grpc_set_header X-Forwarded-Port ${PUBLIC_PORT};
    grpc_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    grpc_set_header X-Forwarded-Proto ${PUBLIC_SCHEME};
}

location ^~ /management.ManagementService/ {
    grpc_pass grpc://${server_upstream};
    grpc_read_timeout 1d;
    grpc_send_timeout 1d;
    grpc_socket_keepalive on;
    grpc_set_header Host \$http_host;
    grpc_set_header X-Forwarded-Host \$http_host;
    grpc_set_header X-Forwarded-Port ${PUBLIC_PORT};
    grpc_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    grpc_set_header X-Forwarded-Proto ${PUBLIC_SCHEME};
}

location ^~ /management.ProxyService/ {
    grpc_pass grpc://${server_upstream};
    grpc_read_timeout 1d;
    grpc_send_timeout 1d;
    grpc_socket_keepalive on;
    grpc_set_header Host \$http_host;
    grpc_set_header X-Forwarded-Host \$http_host;
    grpc_set_header X-Forwarded-Port ${PUBLIC_PORT};
    grpc_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    grpc_set_header X-Forwarded-Proto ${PUBLIC_SCHEME};
}

location ^~ /api/ {
    proxy_pass http://${server_upstream};
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Host \$http_host;
    proxy_set_header X-Forwarded-Port ${PUBLIC_PORT};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto ${PUBLIC_SCHEME};
    proxy_read_timeout 1d;
}

location ^~ /oauth2/ {
    proxy_pass http://${server_upstream};
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Host \$http_host;
    proxy_set_header X-Forwarded-Port ${PUBLIC_PORT};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto ${PUBLIC_SCHEME};
    proxy_read_timeout 1d;
}

location ^~ / {
    proxy_pass http://${dashboard_upstream};
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Host \$http_host;
    proxy_set_header X-Forwarded-Port ${PUBLIC_PORT};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST \$remote_addr;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$http_connection;
    proxy_set_header X-Forwarded-Proto ${PUBLIC_SCHEME};
    proxy_http_version 1.1;
    add_header X-Cache \$upstream_cache_status;
    add_header Cache-Control no-cache;
    proxy_ssl_server_name off;
    proxy_ssl_name \$proxy_host;
${hsts_header}
}
EOF
}
